### ISSUE TITLE
How to build and run? (continued)

### ISSUE THREAD

**Issue by k0001** [LedgerHQ/ledger-wallet-ripple#11]
Thanks for your quick reply @amougel 

I am opening another issue because GitHub doesn't allow me to re-open #10 

I don't see any folder `build/target/chrome-app`, so I suppose you mean `target/chrome-app`. I tried running the following:

```
$ sbt bulid
$ nw target/chrome-app/
```

But what I get is a window with a message saying 

```
Invalid package 

There is no 'package.json' in the package, please make sure the 'package.json' 
is in the root of the package.
```

Can you share some more instructions? I can then write them down in a README file.

**Comment by k0001** [comment]
(By the way, I am not familiar with the tooling being used in this project)

**Comment by amougel** [comment]
You are right, the path is only target/chrome-app.
You have to launch  `nw target/chrome-app/.` (with a dot at the end)
nw will automatically read the manifest file

PS: You can still answer after the thread is closed.
PPS: No need for you to write a README, one should be available soon
