### ISSUE TITLE
unable to start "/usr/bin/Ledger" after installation

### ISSUE THREAD

**Issue by hauweg** [LedgerHQ/ledger-wallet-ripple#12]
i am using xubuntu and installed the deb64.

installation seemed to work fine, but when i want to start the application via GUI, i get the following system prompt: 

Befehl konnte »/usr/bin/Ledger Wallet Ripple« nicht ausführt werden / Kindprozess »/usr/bin/Ledger« konnte nicht ausgeführt werden (Datei oder Verzeichnis nicht gefunden)

i try to translate it to english:

Command »/usr/bin/Ledger Wallet Ripple« could not be executed / Child process »/usr/bin/Ledger« could not be be executed (Could not find file or directory)

do you have any ideas what i can do?

thanks in advance  ♥ ♥ ♥

**Comment by amougel** [comment]
the intaller might not be compatible with all linux distributions.  In that case, you can download the [x64 zipped version for linux](https://github.com/LedgerHQ/ledger-wallet-ripple/releases/download/1.0.2/ledger_wallet_ripple_linux_x64.zip), extract it and run 

```
cd ledger_wallet_ripple_linux_x64
chmod +x Ledger\ Wallet\ Ripple
./Ledger\ Wallet\ Ripple
```
