### ISSUE TITLE
Fedora 26 install conflict with package

### ISSUE THREAD

**Issue by edmund3333** [LedgerHQ/ledger-wallet-ripple#15]
command:  rpm -i ledger-wallet-ripple-x86_64.rpm
result:

file /usr from install of ledger-wallet-ripple-x64-1-3.x86_64 conflicts with file from package sbt-0.13.15-1.noarch
	file /usr/share from install of ledger-wallet-ripple-x64-1-3.x86_64 conflicts with file from package sbt-0.13.15-1.noarch
	file / from install of ledger-wallet-ripple-x64-1-3.x86_64 conflicts with file from package filesystem-3.2-40.fc26.x86_64
	file /usr from install of ledger-wallet-ripple-x64-1-3.x86_64 conflicts with file from package filesystem-3.2-40.fc26.x86_64
	file /usr/bin from install of ledger-wallet-ripple-x64-1-3.x86_64 conflicts with file from package filesystem-3.2-40.fc26.x86_64
	file /usr/share from install of ledger-wallet-ripple-x64-1-3.x86_64 conflicts with file from package filesystem-3.2-40.fc26.x86_64
	file /usr/share/applications from install of ledger-wallet-ripple-x64-1-3.x86_64 conflicts with file from package filesystem-3.2-40.fc26.x86_64

what to do?
i tried building it from source but it was not possible for me...

Thanks

**Comment by checco** [comment]
I have your same problem with Fedora 26. So, I'm using the zip version (https://apps.ledgerwallet.com/ripple/download/linux_64) available in the website and it works

**Comment by edmund3333** [comment]
Thanks for the hint but i can't figure out how to use this zip file on fedora.

**Comment by amougel** [comment]
```
unzip ledger_wallet_ripple_linux_x64_1.0.3.zip
cd ledger_wallet_ripple_linux_x64_1.0.3
sudo chmod +x LedgerWalletRipple
./LedgerWalletRipple
```
