### ISSUE TITLE
Ripple Wallet App Not Working with Windows 10

### ISSUE THREAD

**Issue by sdweber** [LedgerHQ/ledger-wallet-ripple#16]
Reopening this issue as it isn't resolved.  I received your email and responded:
Greetings,

Thanks for getting back with me.

I’ve tried all three of your suggestions below…prior to sending in the trouble report…but no luck.  I’ve even tried running the app and device on two other machines…all Windows 10, as that is all I have…but with no luck.  I've also ensured my anti-virus (Bitdefender) is disabled...still no luck.

At this point, I have my XRP sitting on an exchange and can’t get it to a safe wallet.  May have to set up and use an online digital wallet as a temporary solution (to move XRP off the exchange)…until I can use my two Ledger Nano S devices.

Please let me know what other options I have.  Can you do a remote login and help?  Would appreciate any help you can provide…I’m feeling a bit exposed and at a dead end.

Scott Weber
 

From: amougel [mailto:notifications@github.com] 
Sent: Sunday, December 17, 2017 3:31 AM
To: LedgerHQ/ledger-wallet-ripple <ledger-wallet-ripple@noreply.github.com>
Cc: Scott Weber <scott@weberorbit.com>; Author <author@noreply.github.com>
Subject: Re: [LedgerHQ/ledger-wallet-ripple] Ripple Wallet App Not Working with Windows 10 (#14)

Hi,
The x64 version of the ledger wallet ripple has indeed some compatibility issues but there is no report of issue about the x86 yet.
If you see the window of the app displaying, this means the launch was successfull and now you have another of the following issues:
•	You have the Ledger Manager, Bitcoin wallet, Ethereum Wallet or Electrum running in the background
•	The ripple app on your device has the setting "Browser support" turned on (which should be turned off in order for the app to be able to work)
•	Try another USB port and cable
If you have issue with the synchronization (incorrect balance, missing transactions and so), make sure you clicked on the "two arrows" on the top right corner of the app after launch. However, because of the recent events, the Ripple node wss://s2.ripple.com (which we do not control but use by default) has difficulties responding and thus, prevent our wallet from synchronizing. You can change the node you want to use, by unplugging your device and clicking on "change node" at the bottom of the opening screen.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by amougel** [comment]
We are working on a new release as the current one seems not to be supported by the new windows updates anymore. 

In the mean time, I would suggest you follow the steps in the [README](https://github.com/LedgerHQ/ledger-wallet-ripple/blob/master/README.md) to build the latest version of the app on your computer and secure your XRP.


PS: Please, try to avoid duplicating threads, the old issue should have been used instead.

**Comment by sdweber** [comment]
Greetings,

Appreciate the info and am glad you are working on a fix to the new Windows updates.  Guessing it was the “Fall Creators” update?

Sorry about the duplicate thread.  I got an email that the issue had been closed and didn’t know I could reopen it…so started a new thread.  Will use that feature from now on.

I looked at the README and think I can follow the instructions.  That said, can you provide a little more info on what this will do for me?  Is it a wallet on my PC, or will it allow me to use the Ledger Nano S?  If the latter, are there instructions I need so I don’t make mistakes (and lose my crypto coins)?

Thanks a bunch for your time and assistance.

Scott

**Comment by amougel** [comment]
Difficult to determine which update created the issue.

If you follow the instructions, you will end up launching the same wallet as if you just installed it the normal way. You will be able to connect your Nano-S and make XRP transaction with it. For more info on how to use XRP with our wallet, go [here](https://ledger.zendesk.com/hc/en-us/articles/115005177349-How-to-install-and-use-XRP-Ripple-)

**Comment by sdweber** [comment]
Attempted to follow the instructions for a manual installation of the ledger ripple wallet via sbt and nwjs.  
The sbt install encountered some warnings and error messages, and I was unable to determine if it installed correctly.  The nwjs download wasn't an install file...just a directory structure...so I don't know what I'm was supposed to do with it.  Would appreciate more detailed instructions for the manual installation.  It is a bit unnerving to blindly install these programs on my PC.

**Comment by amougel** [comment]
New release fixing the issue [here](https://github.com/LedgerHQ/ledger-wallet-ripple/releases/tag/1.0.3)
