### ISSUE TITLE
Ledger Wallet Ripple unable to start (debian 9)

### ISSUE THREAD

**Issue by FoUStep** [LedgerHQ/ledger-wallet-ripple#18]
sudo dpkg -i ledger_wallet_ripple_linux_x86.deb 
(Reading database ... 209299 files and directories currently installed.)
Preparing to unpack ledger_wallet_ripple_linux_x86.deb ...
Unpacking ledger-wallet-ripple-ia32 (1-2) over (1-2) ...
Setting up ledger-wallet-ripple-ia32 (1-2) ...
Processing triggers for gnome-menus (3.13.3-9) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...

Installation without issues. However when I want to start the app:
_/usr/bin/Ledger\ Wallet\ Ripple_

Dec 20 08:54:36 step /usr/lib/gdm3/gdm-x-session[1591]: /bin/bash: line 1: Ledger: command not found

It's like it doesn't add the "\\" for the entire application name when starting, so it tries to start:
_/usr/bin/Ledger_

Which doesn't seem to work. Anyone any idea?

**Comment by amougel** [comment]
For the moment you can rename the launcher to match the shortcut's path : `mv /usr/bin/Ledger\ Wallet\ Ripple /usr/bin/Ledger` or create a new shortcut or go directly launch /usr/bin/Ledger\ Wallet\ Ripple. 

The issue will not be here anymore in the coming release.

**Comment by FoUStep** [comment]
Renaming the launcher like you suggested does not solve the problem. It's a symlink to _/usr/share/ledger_wallet_ripple/Ledger\ Wallet\ Ripple_:
_bin/bash: line 1: Ledger: command not found_

I tried to change _/usr/share/ledger_wallet_ripple/Ledger\ Wallet\ Ripple_ to _/usr/share/ledger_wallet_ripple/Ledger_ to no avail.

The file has executable rights.
