### ISSUE TITLE
Stuck loading nw.js

### ISSUE THREAD

**Issue by Nickrohrb** [LedgerHQ/ledger-wallet-ripple#2]
When i open the ledger app it stays stuck loading on the nw.js page.

I was wondering what's going wrong?

**Comment by amougel** [comment]
Which package did you download?

**Comment by Nickrohrb** [comment]
The first one i could download on the ledgerwallet website, I wasnt aware that there are more versions?
I have already tried to uninstall and install

When i open the app it only says: 

nw.js v0.22.3
node v7,10.0
chronium....
commit hash......

**Comment by amougel** [comment]
Which OS are you on? Mac, Windows, Linux  32/64bits ?
Can you tell me the name of the installer you downloaded?
It should be something like :  "ledger_wallet_ripple_osx/win/linux....

**Comment by Nickrohrb** [comment]
On windows 32bit, i downloaded: setup_ledger_wallet_ripple_win_x86

**Comment by amougel** [comment]
Ok, thank you for the report, I will correct this and get back to you when everything is back to normal.

**Comment by amougel** [comment]
The error has been corrected you can now download it again from the website.

**Comment by Nickrohrb** [comment]
I downloaded it again from the website, but it still stays stuck on the same grey screen saying: nw.js

**Comment by amougel** [comment]
The link has been refreshed it is working now. Sorry for the delay
