### ISSUE TITLE
New Release - x64 vs x86

### ISSUE THREAD

**Issue by sdweber** [LedgerHQ/ledger-wallet-ripple#20]
Greetings,

Received the email notification about the fix for Windows 10 (and other issues).  Great job and many thanks! 

Please let me know if the fix applied to the x64 version, x86 version, or both versions.

I'm excited to finally start using my Ledger Nano S!  Appreciate your help.

Scott

**Comment by amougel** [comment]
This is a fresh release for all platforms and architectures (x86 / 32bits  and x64 / 64bits).
