### ISSUE TITLE
New HW Ripple Wallet Not Working

### ISSUE THREAD

**Issue by sdweber** [LedgerHQ/ledger-wallet-ripple#21]
Greetings,

A quick note to let you know I tried installing the new HW Ripple Wallet release (both the x64 and x86 versions) and had no luck on my Windows 10 machine.  Note I have to Ledger Nano S units, and they both fail to work with the desktop software.

I followed all the recommended practices...Ledger Manager not running, browser support set to "No", anit-virus turned off, etc. 

Scott

**Comment by sdweber** [comment]
Update.  I still have been unable to get the x64 version to run, but after restarting my computer and turning off anti-virus, I have been able to get the x86 version to work.  Not sure why the x64 version won't work.  When I start the app, the cursor icon spins for a few seconds and then disappears...the app doesn't start.

**Comment by amougel** [comment]
Did you manage to see the first screen that prompts :

"To begin, connect and unlock your Ledger Wallet.
Then, open the Ripple app on your device."

**Comment by sdweber** [comment]
Hi.  As mentioned in my update note, I'm able to run the x86 version now.

However, I haven't been able to execute the x64 version running on my machines with Windows 10.  If I install and run this version, the cursor changes briefly to indicate the program is loading, but it stops/aborts...no screen/menu comes up at all.  I then pull up Task Manager and see the process is running and have to kill the process (end task) manually.

**Comment by mhanagan** [comment]
Hi,
I'm having the exact same issue on Win10 x64. Will test with the x86 version and disable antivirus

Thanks,

Matt

**Comment by mhanagan** [comment]
yeah x86 worked. Note that the x64 version also looks like it installed the my x86 folder so not sure if that might be the issue.

**Comment by sdweber** [comment]
Another update from my original report.  The x86 version even works great now with my Bitdefender running.  Didn't grant any special access/permissions in Bitdefender.  The x64 version is still a no-go though, at least for my machines running Windows 10.

**Comment by OjhaPrashant** [comment]
I am also having the same issue with the version downloaded from Ledger websites. I am not sure if If it is safe to use x86 version as its not mentioned anywhere on the Ledger website.

**Comment by amougel** [comment]
To make it clear, the Ledger Website does NOT make you download the latest release yet. Only these specific link do : 
[x64](https://github.com/LedgerHQ/ledger-wallet-ripple/releases/download/1.0.3/setup_ledger_wallet_ripple_win_x64_1.0.3.exe) and [x86](https://github.com/LedgerHQ/ledger-wallet-ripple/releases/download/1.0.3/setup_ledger_wallet_ripple_win_x86_1.0.3.exe)

Regarding the issue, if you truly downloaded the 1.0.3 release, this release is packed with NWJS v0.27.2 which is the latest stable version. I'll search on their side what might prevent some w10 computers not to be able to launch it. Can you install and launch NWJS alone? -> [x64](https://dl.nwjs.io/v0.27.2/nwjs-v0.27.2-win-x64.zip) or [x86](https://dl.nwjs.io/v0.27.2/nwjs-v0.27.2-win-ia32.zip)

@ojha1730 x86 or x64 is a matter of architecture of your computer, like mac or windows, not a matter of security.

**Comment by OjhaPrashant** [comment]
@amougel I did download the x86 version that seems to be working fine. However when i launch it, prompts to download 1.0.3 that is basically points to x64. So in general x64 version has some issues that does not allow users to use ledger nano s to store XRP on wallet.

**Comment by amougel** [comment]
@ojha1730 You must have downloaded the 1.0.2 (our website only distributes the 1.0.3 since around 11 am GMT+1.  Since all posters here seem to have downloaded older versions I close the thread.
