### ISSUE TITLE
Can not enter recipient in new Version

### ISSUE THREAD

**Issue by franz101** [LedgerHQ/ledger-wallet-ripple#22]
Can neither type, paste or any other way to add the sender... The type field works for amount but not the adress of the recipient.

**Comment by amougel** [comment]
Likely, you are trying to copy/paste more than an address (likely from shapeshift where special characters are atached to the actual address ). An XRP address should start with a small "r".

For usage issue, please refer to our support :  https://ledger.zendesk.com/hc/en-us
