### ISSUE TITLE
Ledger Wallet Ripple not working(neither x86 setup nor x64)

### ISSUE THREAD

**Issue by mna2016** [LedgerHQ/ledger-wallet-ripple#23]
I am running windows 7.

I have tried both the setup files. The nano s device has "browser support = NO" by default. AV is disabled. After double clicking the app nothing happens. Although task manager shows a process for ripple wallet, which I have to kill manually.

The app is not opening at all. 

Please help out.

Thanks!

**Comment by amougel** [comment]
Can you download this [file](https://ufile.io/xn8ka) , uncompress it and execute the nw.exe file inside? This is an unpackaged release of the app. That would help me detect if the issue comes from nwjs or the boxing we do.

Thanks

**Comment by ProfMoonbeam** [comment]
Hey amougel - I'm also experiencing this issue. Happy to help troubleshoot but need this resolved asap if possible. Thanks!

**Comment by lenkii** [comment]
Had the same issue. problem is resolved after downloading your file and manual starting the app.

**Comment by amougel** [comment]
In that case we'll change the installation method for windows in the coming weeks. Thanks for he feedback.

**Comment by ProfMoonbeam** [comment]
amougel - any update on not being able to open the app on windows? Is there any other way I can move my ripple to my device? If not, is there a wallet you recommend in the mean time? Thanks!

**Comment by Hoegje** [comment]
Same here, commenting to get an update

**Comment by amougel** [comment]
The file in the [link ](https://ufile.io/xn8ka) above is not working for you? @ProfMoonbeam  @Hoegje

**Comment by Hoegje** [comment]
I can't test the link on the laptop I have here. After unpacking the 7z file, Symantec Endpoint Protection is always putting the nw.exe in Quarantaine whenever I try to start it. I can't disable or whitelist anything in the program. I'll have to try on another computer, I guess. 

FYI: When I download setup_ledger_wallet_ripple_win_x86_1.0.3.exe it also immediately removed by Symantec, but the setup_ledger_wallet_ripple_win_x64_1.0.3.exe is not!

**Comment by Hoegje** [comment]
@amougel : I restored the Quarantined exe, and started it really fast, and then it worked and gave me the login screen. Don't have my Nano S with me atm, but that seems to be working. Any idea what the difference is between the official one and this download link? I could go and start building from source, but I would rather not have to go that way if not needed.

**Comment by pennythepup** [comment]
Hi @amougel 

I just received my ledger nano s and am having this same problem.  Working on Windows 7.  Have downloaded Ripple wallet without chrome open and with antivirus disabled. 

When I attempt to open it, eventually a window appears and it is Not Responding/frozen.  In application manager 5-8 instances of it will open and close in no obvious pattern. 

I attempted to download from your link, and there's nothing downloadable on that website except some ad banners.  There is a central link indicating I need a premium account to download the file you reference.

Please advise.

**Comment by ProfMoonbeam** [comment]
Amougel- this is really frustrating. I paid $170 for this thing and I can’t get the ripple app to open. I’ve been patient and have waited since December for you to fix it, but it clearly isn’t a priority for you.

**Comment by amougel** [comment]
@ProfMoonbeam  I provided a working solution on Dec 22th. I ll reupload it in the next days for you to download. The official release is delayed for reasons that are beyond my reach.

**Comment by amougel** [comment]
@ProfMoonbeam  @pennythepup   You can download the installer [here](https://ufile.io/k4hny)
