### ISSUE TITLE
Raspberry Pi Ripple Wallet

### ISSUE THREAD

**Issue by theninkynonk** [LedgerHQ/ledger-wallet-ripple#24]
Have downloaded and installed the 32 bit deb file for the Ripple wallet but when launching, you get nothing. The sand timer appears on the cursor, then nothing. As far as I can see, nothing is happening in the task manager. Any thoughts?

**Comment by amougel** [comment]
I ping you when the package is fixed. Some files have indeed root as owner, which explain that nothing launches.

**Comment by theninkynonk** [comment]
Would it work if I was logged in as root? Apologies - rather new to Linux

**Comment by amougel** [comment]
My bad, the issue seems to come from the 32bits NWJS package for linux. Download the 1.0.2 release while we work on a fix
