### ISSUE TITLE
Unable install Ledger Nano S ripple wallet

### ISSUE THREAD

**Issue by GitItSachin** [LedgerHQ/ledger-wallet-ripple#27]
I am getting access is denied for Ipersist file when I'm trying to install the wallet.
attaching the image below
![image](https://user-images.githubusercontent.com/34856747/34353893-90f1edfa-e9df-11e7-86c6-594fa91ab427.png)

Sachin

**Comment by amougel** [comment]
This might be caused by bitdefender antivirus, see this[ similar situation ](https://support.easyworship.com/support/solutions/articles/24000014886-ipersistfile-save-failed-error-while-installing)

**Comment by GitItSachin** [comment]
After the installing I'm getting this 
![image](https://user-images.githubusercontent.com/34856747/34387874-776dd806-eae5-11e7-82f3-8fcb821be090.png)

please help
