### ISSUE TITLE
Cant send xrp

### ISSUE THREAD

**Issue by ormirand** [LedgerHQ/ledger-wallet-ripple#28]
Im a user and when trying to type xrp send address symbols dont type . Pasting address does not work. When scanning QR code "ripple:" is automatically added to address and wont allow to delete, backspace nor cut out. If left as is invalid address is produced.

**Comment by amougel** [comment]
There should be no symbol in a ripple addresss.

Can you send the qrcode and tell us where you got it from so we can check the parsing?

**Comment by ormirand** [comment]
Address:
rwfGzgd4bUStS9gA5xUhCmg1J86TMtmGMo?dt=51307465

On Dec 26, 2017 8:46 AM, amougel <notifications@github.com> wrote:

There should be no symbol in a ripple addresss.

Can you send the qrcode and tell us where you got it from so we can check the parsing?

**Comment by ormirand** [comment]
![screenshot_20171226-084814 6](https://user-images.githubusercontent.com/34859918/34357096-86efc2ba-ea1a-11e7-9163-c44721fdcf44.jpg)

rwfGzgd4bUStS9gA5xUhCmg1J86TMtmGMo?dt=51307465
Shapeshift

**Comment by amougel** [comment]
rwfGzgd4bUStS9gA5xUhCmg1J86TMtmGMo <-- this is the address you have to copy or type to the recipient field

51307465 <-- this is the destination tag that you can enter by selecting "advanced mode"

Thanks for the qrcode.

**Comment by ormirand** [comment]
thanks
