### ISSUE TITLE
Provide checksum for all binaries

### ISSUE THREAD

**Issue by dstnbrkr** [LedgerHQ/ledger-wallet-ripple#29]
There are [download links on this page without checksums](https://www.ledgerwallet.com/apps/ripple). Without a checksum, users cannot verify that the binary they receive is intact / not compromised. Checksums were also requested in #9 and would have increased confidence that the virus scanner had a false positive.

**Comment by amougel** [comment]
All  linux download have a signature and OSX/Win downloads are signed with our certificate. We'll add info/checksums on our webpage soon. Thanks for the feedback

**Comment by stevesbrain** [comment]
@amougel I noticed these aren't GPG signatures. What type of signature are they? Some form of OpenSSL signature?

**Comment by amougel** [comment]
Yes, openssl signatures.

**Comment by stevesbrain** [comment]
No worries; is the hash algorithm specified anywhere?

**Comment by amougel** [comment]
Forgot to mention :/ , we signed the sha256 of the file
[help](https://stackoverflow.com/questions/10782826/digital-signature-for-a-file-using-openssl)

**Comment by stevesbrain** [comment]
Ah, that's why I could never get it to verify :P Could be worth mentioning that in release announcements? :)
