### ISSUE TITLE
The app name is displayed as "nwjs" in Finder (macOS)

### ISSUE THREAD

**Issue by piyodev** [LedgerHQ/ledger-wallet-ripple#30]
The latest Ledger Wallet Ripple app (1.0.3) name is displayed as "nwjs" in Finder on macOS.
I found it happens when my macOS is _non-English_ environment.

I think it should be fixed as soon as possible because users (especially non-English speaking users like Japanese) may think the new version is malformed.

It looks information in localized string files is incorrect.
(e.g. macOS app bundle > Contents > Resources > ja.lproj > InfoPlist.strings)

I think "nwjs" is wrongly assigned to CFBundleDisplayName. 
`CFBundleDisplayName = "nwjs";`

When I changed it to "Ledger Wallet Ripple", the app name is displayed correctly.

Could you please check this issue? Thanks so much for developing great hardware and app.

My environment:
- Ledger Wallet Ripple package: ledger_wallet_ripple_osx_1.0.3.pkg
- OS: macOS 10.13.1
- Language: Japanese

**Comment by amougel** [comment]
Thanks for the info. We correct this soon.
