### ISSUE TITLE
transfer not found

### ISSUE THREAD

**Issue by loganve1** [LedgerHQ/ledger-wallet-ripple#32]
I sent was transferring ripple from nano s to my exchange and after a few of the issues like no funds available it went through. It never came to  y account and when I click the transaction under last operations it shows transaction not found.

**Comment by amougel** [comment]
The ripple network is under heavy load at the moment, if you don't see the transaction under https://xrpcharts.ripple.com/#/transactions , this means you have to try to send it again.
