### ISSUE TITLE
Application name - macOS

### ISSUE THREAD

**Issue by kaspersoerensen** [LedgerHQ/ledger-wallet-ripple#36]
The Application name shows "nwjs" on my Mac. That is a bit odd.

![skaermbillede 2018-01-08 kl 19 52 27](https://user-images.githubusercontent.com/2018894/34686947-82cded2c-f4ad-11e7-9ea6-b8846c8af9e7.png)

**Comment by amougel** [comment]
It is fixed in the next released.
