### ISSUE TITLE
Cannot open ripple wallet on windows

### ISSUE THREAD

**Issue by ProfMoonbeam** [LedgerHQ/ledger-wallet-ripple#37]
Hey amougel - i have tried each of the ripple exe versions and am still unable to open the wallet on windows. Will this prevent be from transferring xrp to my device? if so, is there an alternative wallet you recommend in the meantime? Need to get it off the exchange

Thanks,

Ryan

**Comment by amougel** [comment]
Have you tried this solution?

> Can you download this [file ](https://ufile.io/xn8ka), uncompress it and execute the nw.exe file inside? This is an unpackaged release of the app. That would help me detect if the issue comes from nwjs or the boxing we do.

**Comment by DaveA-W** [comment]
I am experiencing the same issue.  I can see the process in Task Manager, but nothing appears on screen.  Your file link is still available so I will try that and report back.

**Comment by DaveA-W** [comment]
Turned out to be Bitdefender blocking it.
