### ISSUE TITLE
Deposit tags

### ISSUE THREAD

**Issue by Razican** [LedgerHQ/ledger-wallet-ripple#39]
Some services require you to to provide a deposit tag along with the recipient address to send them money, but I don't see how to do this using this wallet. How can it be done?

**Comment by amougel** [comment]
You have a tutorial [here](https://support.ledgerwallet.com/hc/en-us/articles/115004147073)

**Comment by Razican** [comment]
Sorry, I didn't know about the advanced mode. Thanks for pointing it out!
