### ISSUE TITLE
Enable signing of requireDestinationTag

### ISSUE THREAD

**Issue by junderw** [LedgerHQ/ledger-wallet-ripple#4]
https://ripple.com/build/gateway-guide/#requiredest

This is not a value transaction, but rather it is a transaction to tell the Ripple network that they can not send XRP to your address without a destination tag.

This is a must for people who wish to receive money from multiple people at sporadic times.

**Comment by amougel** [comment]
This feature will only be implemented in the next desktop application that regroups all currencies supported by our devices.

**Comment by junderw** [comment]
Thanks for the reply. Any ETA on when that app will be released?

**Comment by amougel** [comment]
We don't have any ETA to provide yet.
