### ISSUE TITLE
Add trust line for Ripple Wallet

### ISSUE THREAD

**Issue by ITTrooper** [LedgerHQ/ledger-wallet-ripple#46]
Hi there
It would be great if there was the possibility to add a trust line and new tokens to the wallet.
This due to the fact that new tokens get on the XRP ledger (e.g. www.allvor.org).

Regards, I.

**Comment by histteacher** [comment]
Try this fix..


https://github.com/WietseWind/xrp-trustline-set-commandline

**Comment by ITTrooper** [comment]
thx! I got some questions:
- I get warnings installing npm install. Why?
- Doesn't has the issuer to be edited as well? Is this Allvor as a Counterparty:  raEQc5krJ2rUXyi6fgmUAf63oAXmF7p6jp ?
Regards!

**Comment by ITTrooper** [comment]
@histteacher It took me some time, but I finally made it and got my ALVs. THANKS A LOT, you made my day!!! 🥇 👍

**Comment by sCLARKware** [comment]
ITTrooper, a few quick questions if you don't mind?

1. After you finished, is there any way to see ALV in the Ledger Wallet Ripple desktop app, or only on an explorer like bithomp.com? 
2. You said it took some time... did you have issues with the code, or just the setup?
3. Did you set the trust flag back to "0"? I'm not exactly sure if there are any repercussions if we leave the trust active.

Thanks so much!

**Comment by ITTrooper** [comment]
1. I can only 'see' the coins on bithomp.com, not in the Ledger Wallet (unfortunately)
2. Just the setup. Getting rid of all Java-classes and so on wasn't that easy, because I'm not very familiar with that.
3. I don't know either if it should be set back to 0 or not. If you have any further information about that, please let me know. Thanks!

I hope my anwers did help you
Regards

**Comment by histteacher** [comment]
Hi all.

Ledger wallet has not been updated to validate or read ALV.  The ledger contains all value records.  The ALV are there.  

Where you set the trust to 10,000,000...just change that to 0.  Be safe, close the trust.
This essentially closes the trust. Run the process from the readme again.

As for the edits, if you are on a Microsoft PC, you can download Visual Studio Code (https://code.visualstudio.com/).  Make sure the contents of GitHub have been unzipped to your "Windows/System32" folder.  Open using the VS Code editor and make the edits based off of the directions. (Make sure you delete the files you have added!!!  Clear your trash; shred anything with passcodes!)

IMPORTANT! --Repetitive 
Once you have run the file with your Ledger, gone to the ALV website to apply/receive the tokens, and verified receipt on bithomp.com, you should set the trust to zero, run it again following the readme directions from the zip, confirm again on bithomp that the trust is set to zero, and delete the all files.  Shred them if you can. make sure all data and trash that may have potentially held your passcode(s) are gone!

**Comment by ITTrooper** [comment]
Sorry I don't get everything I have to do.
1. I have to edit offline-with-mnemonic.js (value : "0"). After I let it run again.
2. What is this all about visualstudio and what files do I have to delete?
3. Where on bithomp can I see the trust?

**Comment by histteacher** [comment]
My apologies.  There are a couple of steps for the checking via bithomp that the trust is set back to zero. I'm going to answer your three points as you have them listed.  You can skip to #3 regarding checking the trust status.  Hopefully this is less confusing. 


1) ---- Setting Trust to Zero ----(this is optional and can always be reopened)...sounds like you did this correctly.

`const Transaction = {
  TransactionType: 'TrustSet',
  Flags: 131072, // tfSetNoRipple
  Account: WalletAddress,
  LimitAmount: {
    currency : "ALV",
    issuer : "raEQc5krJ2rUXyi6fgmUAf63oAXmF7p6jp",
    value : "0"
  },
  Fee: 15,
  LastLedgerSequence: null
}`

2) VisualStudio is what I use to edit the .js files.  However, you could use whatever works best for you.  

3) Seeing the trust...
       1. Enter you acct into bithomp
       2. Find your transaction ID for when you closed the trust...will say "Trustline" and near the ranked number it should say #2. Click on the Transaction ID, copy it.
       3. Go to Ripple's XRP Charts to pull the transaction from the ledger. Paste the txn ID from Bithomp and click Go.  
               Ripple's XRP Charts:  https://xrpcharts.ripple.com/#/transactions
           Should Read:

>            DESCRIPTION:
                This is a TrustSet transaction.
                It establishes 0 as the maximum amount of ALV from raEQc5krJ2rUXyi6fgmUAf63oAXmF7p6jp 
                that rxxxxx(your_acct)xxxxxx is willing to hold.
                The transaction's sequence number is 2

I hope that helps.

**Comment by ITTrooper** [comment]
There's another parameter that has to be set, then it works
let AccountSequence = (+1)

Great I made it! Thank you very much for your patience and support! 😃 👍

**Comment by cious1** [comment]
Are IOUs and trustlines a planned added feature in the future for the ledger ripple software? Thank you for your support and time!

**Comment by allencatt** [comment]
found this thread while googling the subject. Unfortunately Im super non technical.  my daughter has to turn my computer on for me.  Is there a non tech way to retrieve the allvor waiting for me? I have been trying since mid April.  Im a long term xrp holder and store my coins on the nano s.  Any help at all would be greatly appreciated

**Comment by histteacher** [comment]
Hi.  Wieste Wind is the developer.   He put together a YouTube video to help.  This is likely the least technical in creating the trust through your ledger.

I am not certain the recent updates by Ledger affect this process.

Here is the video: https://youtu.be/U_bDHgZ0wuc

Sincerely.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by allencatt** [comment]
Thanks for all your help.  Im still scared out of my mind that i will really mess this up.  

Allencatt1

**Comment by histteacher** [comment]
I was too when I first tried it.  :) Wieste is a trusted developer within the XRP community.

Best.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
