### ISSUE TITLE
Release 1.1.1 has misspelling of app name in OSX

### ISSUE THREAD

**Issue by gotjoshua** [LedgerHQ/ledger-wallet-ripple#48]
![ledgerwalletripple-osxapp-fileinfo](https://user-images.githubusercontent.com/8686454/38810274-339a1dd4-417e-11e8-84c7-3f11bfdd3a0d.png)
![ledgerwalletripple-osxapp-names](https://user-images.githubusercontent.com/8686454/38810275-33b4f866-417e-11e8-9028-c39a98aeec64.png)

Also the Version Number as reported in File Info does not match the Release Version in github

Also the download page on [ledgerwallet.com](https://www.ledgerwallet.com/apps/ripple) links to 1.0.3

**Comment by amougel** [comment]
Hi, thanks for pointing the typo. This version is not released yet and will not be. 1.1.2 is the next official release. In the meantime, we ll fix the typo in the 1.1.1 files
