### ISSUE TITLE
Ripple secret seed generation

### ISSUE THREAD

**Issue by junderw** [LedgerHQ/ledger-wallet-ripple#5]
Upon review of the ledger blue app for ripple, it seems as though you are generating `m/44'/144'/0'/0/0` and using the private key for that key as the direct private key of the ripple address.

This makes it difficult to export the wallet and reuse in outside APIs (like rippled) because they use a Secret seed (which afaik is 16 bytes of random data encoded in ripple's special base58check) and from that seed Ripple uses its own special algorithm to generate the private key that becomes the public key and eventually the ripple address.

afaict ledger seems to be using the private key directly, and not going through the ripple secret derivation algorithm... so it would be impossible to export the key in the format that rippled accepts.

Perhaps:

1. take the private key 32 bytes from the derived key and bytes[:32] xor bytes[32:] to get the 16 bytes for encoding into the ripple secret.
2. derive the private key and other info according to ripple standards.
3. On your github explain how the derivation from BIP39 phrase to the ripple secret works so that anyone who wants to recover can easily do so using rippled or other wallets (which all take ripple formatted secret only as import input)

People already using it would be out of luck, but if the wallet objects have versioning it shouldn't be too hard.

**Comment by amougel** [comment]
Hello

Thank you for the suggestion, but our users already use the ripple wallet and changing the use of a private key into the use of a secret would force them to move all their assets to other wallets and would lead to many users loosing their assets due to mistakes during the process.

So you can't implement this alternative.

Best regards
