### ISSUE TITLE
Ethereum Wallet v 0.8.10 shows wrong QR-code

### ISSUE THREAD

**Issue by ETYMOLOGIA** [LedgerHQ/ledger-wallet-ripple#7]
I've noticed that Ethereum Wallet v. 0.8.10 shows wrong QR-code. It swaps cases of some symbols. ETH sent to QR-code address generated by the wallet SW never received the payment sent from the other address (Coinbase one).

**Comment by btchip** [comment]
Sorry, what ? 

You're referencing a version of the Ethereum application that we don't have on the Ripple wallet project
