### ISSUE TITLE
x64 is not a valid architecture

### ISSUE THREAD

**Issue by Razican** [LedgerHQ/ledger-wallet-ripple#8]
Hello, I'm having real trouble to install the 64 bit RPM package in my Fedora. The architecture says x64, but that does not exist, and of course DNF protests and won't let me install it. Not sure if it was meant to be x86_64 (for Intel/AMD based processors) or aarch64 (for ARM processors), both 64 bit architectures, but in any case, x64 does not exists and won't let me install it. In my case, I'm trying to install it in a x86_64 processor.

**Comment by amougel** [comment]
Can you try this package https://github.com/LedgerHQ/ledger-wallet-ripple/releases/download/1.0.2/ledger-wallet-ripple-x86_64.rpm

**Comment by vbroskas** [comment]
**for anyone else having this problem, it seems it had to do with trying to install the wallet using unbuntu software-center. The install ran fine when i used:
``` 
   $sudo dpkg -i /pathToFile
   $sudo apt-get install -f
```
 

I am also getting some serious warnings trying to install the 64bit Deb file on my system (unbuntu 16.04). Warnings about the file not being safe:

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

```Lintian check results for /home/lb/Downloads/ledger_wallet_ripple_linux_x64.deb:
E: ledger-wallet-ripple-x64: arch-independent-package-contains-binary-or-object usr/share/ledger_wallet_ripple/Ledger Wallet Ripple
E: ledger-wallet-ripple-x64: arch-independent-package-contains-binary-or-object usr/share/ledger_wallet_ripple/lib/libffmpeg.so
E: ledger-wallet-ripple-x64: arch-independent-package-contains-binary-or-object usr/share/ledger_wallet_ripple/lib/libnode.so
E: ledger-wallet-ripple-x64: arch-independent-package-contains-binary-or-object ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: ledger-wallet-ripple-x64: maintainer-address-malformed root <root@ubuntu>
E: ledger-wallet-ripple-x64: wrong-file-owner-uid-or-gid usr/ 1000/1000
E: ledger-wallet-ripple-x64: wrong-file-owner-uid-or-gid usr/bin/ 1000/1000
E: ledger-wallet-ripple-x64: wrong-file-owner-uid-or-gid usr/bin/Ledger Wallet Ripple 1000/1000
E: ledger-wallet-ripple-x64: wrong-file-owner-uid-or-gid ... use --no-tag-display-limit to see all (or pipe to a file/program)```

Has anyone else gotten this?
