### ISSUE TITLE
xxx

### ISSUE THREAD

**Issue by afsarker** [LedgerHQ/ledger-wallet-ripple#9]

**Comment by riknedsin** [comment]
Seriously, what is it?
[https://www.virustotal.com/ru/file/924b60d124f5fa951e4bc93e2fd8e3c954fb86c19d590bcbab7648d06bc035ec/analysis/1512950930/](url)

**Comment by stevesbrain** [comment]
Pretty sure those are just generic detections for compilers/packagers (not uncommon with a lot of executables). You'd probably be seeing a few more hits if it was a legitimate concern
